<script type="text/javascript" src="/media/qtip/jquery.js"></script>
<script type="text/javascript" src="/media/qtip/qtip.js"></script>
<script type="text/javascript" src="/media/qtip/qtip.min.js"></script>
<script type="text/javascript" src="/media/help.js"></script>
<script type="text/javascript" src="/media/form-show-hide.js"></script>
<script type="text/javascript" src="/media/jquery.min.js"></script>
<script type="text/javascript" src="/media/expand.js"></script>
<style type="text/css">@import url("/media/qtip/esupActivation.css");</style>
<style type="text/css">@import url("/media/qtip/collapse.css");</style>